name: Implementor-test

on: 
  workflow_dispatch:
    inputs:
      mod:
        description: Modification
        required: true
        type: choice
        options:
          - interface
          - class
          # - Advanced
      class:
        description: Class for tests
        required: true
        type: choice
        options:
          - Implementor

jobs:
  Test-solution:
    uses: ./.github/workflows/multi-platform_test.yml
    with:
      homework: implementor
      mod: ${{ inputs.mod }}
      class: ${{ inputs.class }}
    secrets:
      token: ${{ secrets.READ_PAT }}